### ISSUE TITLE
Is the repository under development?

### ISSUE THREAD

**Issue by magicDGS** [ThomasTaus/Nest#1]
@ThomasTaus - you told me the other day in person that it is better to use the [`poolSeq` package](https://github.com/ThomasTaus/poolSeq) instead of `Nest`, because it has some bug fixes and it is under development. From that, I assume that this repository is not any longer under development, and thus you should inform the users that they should move to `poolSeq`.

I recommend to:
* Add a big header to the README with a note warning about the deprecation and pointing to the other package
* Add to the repository description a deprecated note
* Mark repository as archived (see more in https://help.github.com/articles/archiving-a-github-repository/)

Nevertheless, I recommend a different way of handling the sharing code between `Nest` and `poolSeq`:
1. I would keep in `Nest` the code for estimating Ne and remove the code for read a sync file
2. I would remove the code for Ne estimation from `poolSeq` (not really necessary)
3. I would decide if the simulation code is better to stay here or in `poolSeq` (I guess that `poolSeq` has better usage)
4. I would decide if some functionality from `Nest` is really required in `poolSeq`, and if so I will import it as a requirement for `poolSeq`

That will make each library to be imported as necessary: `Nest` for estimating Ne from vectors (general functions, as described on the paper); `poolSeq` for Pool-Seq data analysis; both for combine analysis.

**Comment by magicDGS** [comment]
@ThomasTaus - Another option if you don't want to maintain this repository anymore is to transfer the ownership to someone willing to maintaining it (maybe Agi, but I can also offer myself in case she doesn't want to).

**Comment by ThomasTaus** [comment]
Dear Daniel,

thank you very much for your feedback. I added a note to the Readme file of Nest, indicating that poolSeq should be used instead.

For usability purposes, all functionality is available in poolSeq, which will be updated regularly.

Cheers,

Thomas
