### ISSUE TITLE
Bug: negative Ne estimates are returned in some cases

### ISSUE THREAD

**Issue by magicDGS** [ThomasTaus/Nest#3]
For some datasets, the returned value of the Ne estimation is negative. As it is described in the manuscript, that should be considered as no drift and thus infinity Ne. The method should return `Inf` in that case, otherwise median value of a window analysis might be distorted.

**Comment by ThomasTaus** [comment]
Thank you very much Daniel for pointing this out. This issue will be fixed in the next release of poolSeq.

**Comment by magicDGS** [comment]
I think that this should be fixed in Nest too. There are putative users that are coming to the Nest repository from the original publication, expecting that it is maintained, and they will have wrong results. We shoulnd't assume that only institute people is using our software, and we should stick to the original publication links as much as possible...
